server:
  servlet:
    context-path: /micrometer-service
  port: 8080

spring:
  application:
    name: micrometer
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, prometheus
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true


